ARG NODE_VERSION

FROM node:${NODE_VERSION}-alpine

RUN apk add --no-cache git libstdc++

ARG USER_ID
ARG GROUP_ID

RUN apk add --no-cache  --virtual .build-deps shadow && \
    ([ "${GROUP_ID}" == "1000" ] || groupmod -g ${GROUP_ID} node) && \
    ([ "${USER_ID}" == "1000" ] || usermod -u ${USER_ID} node ) && \
    mkdir -p /home/node/.vscode-server /home/node/.vscode-server-insiders /home/node/.ssh && \
    chown -R node:node /home/node/ && \
    chmod 755 /home/node/.ssh && \
    apk del .build-deps && rm -rf /var/cache/apk/*

ARG EXTRA_PKGS

RUN [ -z "$EXTRA_PKGS" ] || (apk add --no-cache $EXTRA_PKGS && rm -rf /var/cache/apk/*)

WORKDIR /app

RUN mkdir node_modules && chown node:node -R /app

ENV NODE_ENV=development

USER node

VOLUME [ "/app", "/app/node_modules" ]

CMD exec /bin/sh -c "trap : TERM INT; (while true; do sleep 1000; done) & wait"
